### ISSUE TITLE
import * not working as expected

### ISSUE THREAD

**Issue by juanda99** [59naga/babel-plugin-add-module-exports#20] opened 2015-12-25 21:45 UTC
import * is not working as expected.

My problem:

i18n/index.js file contents:

```
export { default as es } from './es'
export { default as it } from './it'
export { default as en } from './en'
```

I try to load localization messages:

```
import * as i18n from 'i18n'
...
const intlData = {
  locale: 'en',
  messages: i18n['en']
}
```

However messages variable is undefined.

When I check the console log with:

```
window.console.log(i18n)
```
I get undefined:

```
Object {__esMOdule: true}
 es:undefined
 get es: function get()
 it: undefined
 get it: function get()
 en: undefined
 get en: function get()
 __proto__: Object
```

Where I should get something like:

```
Object {__esMOdule: true}
 es: Object
 it: Object
 en: Object
 __proto__: Object
```

If I remove your plugin in my webpack configuration everything works ok:
```
loaders: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          cacheDirectory: true,
          plugins: ['transform-runtime', 'add-module-exports'],
          presets: ['es2015', 'react', 'stage-0'],
```

**Comment by davezuko** [comment] 2015-12-26 21:43
@juanda99 thanks for reporting this, curious to see what comes out of it.

**Comment by lijunle** [comment] 2016-01-13 16:56
**TL;TD;** use ` i18n.en` instead of ` i18n['en']`

---

The file `i18n/index.js` is transformed into the following by Babel

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _es = require('./es');

Object.defineProperty(exports, 'es', {
  enumerable: true,
  get: function get() {
    return _es.default;
  }
});

var _en = require('./en');

Object.defineProperty(exports, 'en', {
  enumerable: true,
  get: function get() {
    return _en.default;
  }
});
```

Notice that, the `es` and `en` are properties and **not** object keys. So, `i18n['en']` will not work - use `i18n.en` instead.

I have no idea why Babel transform `export as from` to property, but this is not the scope of this plugin.

**Comment by lijunle** [comment] 2016-01-13 17:22
Hmm... Babel@5 transform the `i18n/index.js` into [object keys](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=export%20%7B%20default%20as%20es%20%7D%20from%20'.%2Fes'%0D%0Aexport%20%7B%20default%20as%20it%20%7D%20from%20'.%2Fit'%0D%0Aexport%20%7B%20default%20as%20en%20%7D%20from%20'.%2Fen') so works fine with `i18n['en']`. I have no idea why Babel@6 changes such behavior.

**Comment by 59naga** [comment] 2016-01-14 20:01
Can fix this problem use the `0.1.3-alpha`.

```js
export { default as es } from './es'
export { default as it } from './it'
export { default as en } from './en'
```

This fix detects the export-from statement of rename been default as described above.
Replace it to the code below.

```js
'use strict';

exports.es = function (obj) {
  return obj && obj.__esModule ? obj['default'] : obj;
}(require('./es'));

exports.it = function (obj) {
  return obj && obj.__esModule ? obj['default'] : obj;
}(require('./it'));

exports.en = function (obj) {
  return obj && obj.__esModule ? obj['default'] : obj;
}(require('./en'));
```

It is not a perfect imitation of `babel@5`.

**Comment by lijunle** [comment] 2016-01-15 01:59
@59naga I think we could better to understand why Babel@6 change its behavior first. **This might be a bug from Babel side.**

**Comment by 59naga** [comment] 2016-01-15 14:51
Right. I will consider the PR of `babel@6`.(this fix will remove probably, sorry)

The following was the unexpectedly:
```js
export {default as foo} from 'old-commonjs-module'
```

In addition, similar problems have [already been reported](https://phabricator.babeljs.io/search/query/tDDycRQbv.dw/#R)

**Comment by lijunle** [comment] 2016-01-15 15:50
Maybe related:

- https://phabricator.babeljs.io/T1337
- https://phabricator.babeljs.io/T2541
- https://phabricator.babeljs.io/T6953

However, no direct answer for why Babel@6 changes the behavior.

**Comment by AgentME** [comment] 2016-01-15 23:46
@lijunle I'm not sure what difference you're seeing between `i18n.en` and `i18n['en']`. There shouldn't be a difference. The following demonstrates this:

```javascript
'use strict';

var foo = {};

Object.defineProperty(foo, 'bar', {
  enumerable: true,
  get: function() {
    return 123;
  }
});

console.log(foo.bar); // 123
console.log(foo['bar']); // 123
console.log(foo.bar === foo['bar']); // true
```

**Comment by lijunle** [comment] 2016-01-16 08:44
@AgentME, you are right! This is my bad. This issue is not related to Babel's property getter. The problem is caused by this plugin.

## Cause

The following is the original code:

```js
export default {
  en: 'this is en'
};
```

Babel@6 transform it to:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  en: 'this is en'
};
```

However, with this plugin, one more assignment will be added at the end of the end:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  en: 'this is en'
};
module.exports = exports['default'];
```

The final assignment will override the `module.exports` object and lost the previous `module.exports.default` object.

In the `i18n/index.js` getter, it retrieves the value from `_es.default` which is `undefined` of course.

```js
var _es = require('./es');

Object.defineProperty(exports, 'es', {
  enumerable: true,
  get: function get() {
    return _es.default; // <--- _es = {en:'this is en'} and _es.default = undefined
  }
});
```

## Solution 1

Override back `module.exports.default` property:

```js
const $$temp = exports.default;
module.exports = exports['default'];
module.exports.default = $$temp;
```

However, it *may* affect the default exports if it has a `default` property.

## Solution 2

From the re-export side, retrieve default value from `_es` directly:

```js
Object.defineProperty(exports, 'es', {
  enumerable: true,
  get: function get() {
    return _es; // <------ notice this
  }
});
```

**Comment by lijunle** [comment] 2016-01-16 09:41
@59naga I think [your fix](https://github.com/59naga/babel-plugin-add-module-exports/commit/ac0b2d63bb43d2dbc1b456055f9a13602a6d1d6e#diff-6d186b954a58d5bb740f73d84fe39073) is implementing the solution 2. :+1: 

In regards to use property getter, I think the reason is to apply live binding. I will open another issue to talk about it if I get time.

**Comment by hzoo** [comment] 2016-01-19 19:25
Merged https://github.com/babel/babel/issues/3282

**Comment by 59naga** [comment] 2016-01-21 16:10
Would compiled as follows at [present](https://github.com/babel/babel/blob/master/CHANGELOG.md#645-2016-01-19).
Update the `babel-preset-es2015` for resolve this issue.

```js
export { default as es } from './es'
export { default as it } from './it'
export { default as en } from './en'
```
into
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _es = require('./es');

Object.defineProperty(exports, 'es', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_es).default;
  }
});

var _it = require('./it');

Object.defineProperty(exports, 'it', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_it).default;
  }
});

var _en = require('./en');

Object.defineProperty(exports, 'en', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_en).default;
  }
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

using

```bash
{
  "scripts": {
    "build": "babel src --out-dir lib6"
  },
  "devDependencies": {
    "babel-cli": "^6.4.5",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-preset-es2015": "^6.3.13"
  },
  "babel": {
    "presets": [
      "es2015"
    ],
    "plugins": [
      "add-module-exports"
    ]
  }
}
```

**Closed** 2016-01-21 16:14 UTC
